/**
 * Error Codes Constants
 * 
 * Centralized error codes used across the application
 * Used in exceptions and error responses
 */

/**
 * Common Error Codes
 */
export const ERROR_CODES = {
  // Resource errors
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  
  // Validation errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  
  // Authentication errors
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  EXPIRED_TOKEN: 'EXPIRED_TOKEN',
  TOKEN_REFRESH_FAILED: 'TOKEN_REFRESH_FAILED',
  
  // Authorization errors
  FORBIDDEN: 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  
  // Database errors
  DATABASE_ERROR: 'DATABASE_ERROR',
  DATABASE_CONNECTION_ERROR: 'DATABASE_CONNECTION_ERROR',
  QUERY_ERROR: 'QUERY_ERROR',
  
  // Business logic errors
  BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  INVALID_STATE: 'INVALID_STATE',
  
  // System errors
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  TIMEOUT: 'TIMEOUT',
  
  // Cache errors
  CACHE_ERROR: 'CACHE_ERROR',
  CACHE_CONNECTION_ERROR: 'CACHE_CONNECTION_ERROR',
} as const;

/**
 * Field-specific Error Codes
 * Used for validation errors with specific fields
 */
export const FIELD_ERROR_CODES = {
  USERNAME: 'VALIDATION_ERROR_USERNAME',
  EMAIL: 'VALIDATION_ERROR_EMAIL',
  PASSWORD: 'VALIDATION_ERROR_PASSWORD',
  NAME: 'VALIDATION_ERROR_NAME',
  COLOR: 'VALIDATION_ERROR_COLOR',
  DATE: 'VALIDATION_ERROR_DATE',
  PRODUCT_ID: 'VALIDATION_ERROR_PRODUCT_ID',
  FEATURE_ID: 'VALIDATION_ERROR_FEATURE_ID',
  PLAN_ID: 'VALIDATION_ERROR_PLAN_ID',
} as const;

/**
 * Resource-specific Error Codes
 */
export const RESOURCE_ERROR_CODES = {
  BASE_PHASE_NOT_FOUND: 'BASE_PHASE_NOT_FOUND',
  BASE_PHASE_CONFLICT: 'BASE_PHASE_CONFLICT',
  BASE_PHASE_DUPLICATE_NAME: 'BASE_PHASE_DUPLICATE_NAME',
  BASE_PHASE_DUPLICATE_COLOR: 'BASE_PHASE_DUPLICATE_COLOR',
  
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_CONFLICT: 'PRODUCT_CONFLICT',
  PRODUCT_DUPLICATE_NAME: 'PRODUCT_DUPLICATE_NAME',
  
  FEATURE_NOT_FOUND: 'FEATURE_NOT_FOUND',
  FEATURE_CONFLICT: 'FEATURE_CONFLICT',
  FEATURE_DUPLICATE_NAME: 'FEATURE_DUPLICATE_NAME',
  
  CALENDAR_NOT_FOUND: 'CALENDAR_NOT_FOUND',
  CALENDAR_CONFLICT: 'CALENDAR_CONFLICT',
  CALENDAR_DUPLICATE_NAME: 'CALENDAR_DUPLICATE_NAME',
  
  IT_OWNER_NOT_FOUND: 'IT_OWNER_NOT_FOUND',
  IT_OWNER_CONFLICT: 'IT_OWNER_CONFLICT',
  IT_OWNER_DUPLICATE_NAME: 'IT_OWNER_DUPLICATE_NAME',
  
  PLAN_NOT_FOUND: 'PLAN_NOT_FOUND',
  PLAN_CONFLICT: 'PLAN_CONFLICT',
  PLAN_DUPLICATE_NAME: 'PLAN_DUPLICATE_NAME',
  
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_CONFLICT: 'USER_CONFLICT',
  USER_DUPLICATE_USERNAME: 'USER_DUPLICATE_USERNAME',
  USER_DUPLICATE_EMAIL: 'USER_DUPLICATE_EMAIL',
} as const;

