/**
 * Auth Module API Documentation Constants
 * 
 * Constants specific to the Auth module for Swagger/OpenAPI documentation
 */

import { API_OPERATION_SUMMARIES, API_RESPONSE_DESCRIPTIONS, HTTP_STATUS_CODES } from '../../common/constants';

/**
 * Auth Module API Operation Summaries
 */
export const AUTH_API_OPERATION_SUMMARIES = {
  REGISTER: API_OPERATION_SUMMARIES.REGISTER,
  LOGIN: API_OPERATION_SUMMARIES.LOGIN,
  LOGOUT: API_OPERATION_SUMMARIES.LOGOUT,
  REFRESH_TOKEN: API_OPERATION_SUMMARIES.REFRESH_TOKEN,
  GET_CURRENT_USER: API_OPERATION_SUMMARIES.GET_CURRENT_USER,
} as const;

/**
 * Auth Module API Response Descriptions
 */
export const AUTH_API_RESPONSE_DESCRIPTIONS = {
  USER_REGISTERED: API_RESPONSE_DESCRIPTIONS.USER_REGISTERED,
  USER_LOGGED_IN: API_RESPONSE_DESCRIPTIONS.USER_LOGGED_IN,
  USER_LOGGED_OUT: API_RESPONSE_DESCRIPTIONS.USER_LOGGED_OUT,
  TOKEN_REFRESHED: API_RESPONSE_DESCRIPTIONS.TOKEN_REFRESHED,
  CURRENT_USER_INFO: API_RESPONSE_DESCRIPTIONS.CURRENT_USER_INFO,
  INVALID_CREDENTIALS: API_RESPONSE_DESCRIPTIONS.INVALID_CREDENTIALS,
  INVALID_REFRESH_TOKEN: API_RESPONSE_DESCRIPTIONS.INVALID_REFRESH_TOKEN,
  USERNAME_EMAIL_EXISTS: API_RESPONSE_DESCRIPTIONS.USERNAME_EMAIL_EXISTS,
  INVALID_INPUT: API_RESPONSE_DESCRIPTIONS.INVALID_INPUT,
  UNAUTHORIZED: API_RESPONSE_DESCRIPTIONS.UNAUTHORIZED,
} as const;

/**
 * Auth Module HTTP Status Codes
 */
export const AUTH_HTTP_STATUS_CODES = {
  CREATED: HTTP_STATUS_CODES.CREATED,
  OK: HTTP_STATUS_CODES.OK,
  NO_CONTENT: HTTP_STATUS_CODES.NO_CONTENT,
  BAD_REQUEST: HTTP_STATUS_CODES.BAD_REQUEST,
  UNAUTHORIZED: HTTP_STATUS_CODES.UNAUTHORIZED,
  CONFLICT: HTTP_STATUS_CODES.CONFLICT,
} as const;

