/**
 * Auth Module API Property Constants
 * 
 * Constants for ApiProperty descriptions and examples specific to Auth module
 */

import { API_PROPERTY_DESCRIPTIONS, API_PROPERTY_EXAMPLES } from '../../common/constants';

/**
 * Auth Module API Property Descriptions
 */
export const AUTH_API_PROPERTY_DESCRIPTIONS = {
  USERNAME: API_PROPERTY_DESCRIPTIONS.USERNAME_OR_EMAIL,
  PASSWORD: API_PROPERTY_DESCRIPTIONS.PASSWORD,
  EMAIL: API_PROPERTY_DESCRIPTIONS.EMAIL,
  FIRST_NAME: API_PROPERTY_DESCRIPTIONS.FIRST_NAME,
  LAST_NAME: API_PROPERTY_DESCRIPTIONS.LAST_NAME,
  ROLE: API_PROPERTY_DESCRIPTIONS.ROLE,
  ACCESS_TOKEN: API_PROPERTY_DESCRIPTIONS.ACCESS_TOKEN,
  REFRESH_TOKEN: API_PROPERTY_DESCRIPTIONS.REFRESH_TOKEN,
  USER_INFO: API_PROPERTY_DESCRIPTIONS.USER_INFO,
} as const;

/**
 * Auth Module API Property Examples
 */
export const AUTH_API_PROPERTY_EXAMPLES = {
  USERNAME: API_PROPERTY_EXAMPLES.USERNAME_ADMIN,
  USERNAME_REGISTER: API_PROPERTY_EXAMPLES.USERNAME,
  EMAIL: API_PROPERTY_EXAMPLES.EMAIL,
  PASSWORD: API_PROPERTY_EXAMPLES.PASSWORD,
  PASSWORD_LOGIN: API_PROPERTY_EXAMPLES.PASSWORD_SIMPLE,
  FIRST_NAME: API_PROPERTY_EXAMPLES.FIRST_NAME,
  LAST_NAME: API_PROPERTY_EXAMPLES.LAST_NAME,
  TOKEN: API_PROPERTY_EXAMPLES.TOKEN_JWT,
} as const;

