/**
 * Auth Module Validation Constants
 * 
 * Constants specific to the Auth module for validation messages
 */

import { FIELD_VALIDATION_MESSAGES } from '../../common/constants';

/**
 * Auth Module Field Validation Messages
 */
export const AUTH_VALIDATION_MESSAGES = {
  USERNAME_REQUIRED: FIELD_VALIDATION_MESSAGES.USERNAME_REQUIRED,
  USERNAME_MIN_LENGTH: FIELD_VALIDATION_MESSAGES.USERNAME_MIN_LENGTH,
  USERNAME_PATTERN: FIELD_VALIDATION_MESSAGES.USERNAME_PATTERN,
  
  EMAIL_REQUIRED: FIELD_VALIDATION_MESSAGES.EMAIL_REQUIRED,
  EMAIL_INVALID: FIELD_VALIDATION_MESSAGES.EMAIL_INVALID,
  
  PASSWORD_REQUIRED: FIELD_VALIDATION_MESSAGES.PASSWORD_REQUIRED,
  PASSWORD_MIN_LENGTH: FIELD_VALIDATION_MESSAGES.PASSWORD_MIN_LENGTH,
  PASSWORD_PATTERN: FIELD_VALIDATION_MESSAGES.PASSWORD_PATTERN,
  PASSWORD_LOGIN_MIN_LENGTH: FIELD_VALIDATION_MESSAGES.PASSWORD_LOGIN_MIN_LENGTH,
} as const;

