/**
 * Features Module Validation Constants
 * 
 * Constants specific to the Features module for validation messages
 */

import { FIELD_VALIDATION_MESSAGES } from '../../common/constants';

/**
 * Features Module Field Validation Messages
 */
export const FEATURE_VALIDATION_MESSAGES = {
  FEATURE_NAME_REQUIRED: FIELD_VALIDATION_MESSAGES.FEATURE_NAME_REQUIRED,
  FEATURE_DESCRIPTION_REQUIRED: FIELD_VALIDATION_MESSAGES.FEATURE_DESCRIPTION_REQUIRED,
  FEATURE_TECHNICAL_DESCRIPTION_REQUIRED: FIELD_VALIDATION_MESSAGES.FEATURE_TECHNICAL_DESCRIPTION_REQUIRED,
  FEATURE_BUSINESS_DESCRIPTION_REQUIRED: FIELD_VALIDATION_MESSAGES.FEATURE_BUSINESS_DESCRIPTION_REQUIRED,
  FEATURE_PRODUCT_ID_REQUIRED: FIELD_VALIDATION_MESSAGES.FEATURE_PRODUCT_ID_REQUIRED,
} as const;

